package tramites_de_iglesia;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Actas extends javax.swing.JFrame {

    //Imagenes
    ImageIcon icon_Actas = new ImageIcon(ClassLoader.getSystemResource("imagenes/Actas.png"));
    
    //Objetos
    Configuraciones config = new Configuraciones();
    
    String datos[] = config.leerArchivo(); //Leer los datos del archivo
    
    ConexionDB DB =  new ConexionDB();
    java.sql.Connection conexion = DB.conectarDB(DB.getDatabase(), datos[0], datos[1], false);
    
    //Modelos para las tablas
    DefaultTableModel modelo_tipos;
    DefaultTableModel modelo_sacramentos;
    DefaultTableModel modelo_actas;
    
    /**
     * Creates new form Actas
     */
    public Actas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Definir los modelos
        modelo_tipos = new DefaultTableModel();
        modelo_sacramentos = new DefaultTableModel();
        modelo_actas = new DefaultTableModel();
        
        //Tabla sacerdotes
        modelo_tipos.addColumn("Id acta");
        modelo_tipos.addColumn("Nombre acta");
        this.table_tipos_actas.setModel(modelo_tipos);
        //Tabla tipos de sacramentos
        modelo_sacramentos.addColumn("Id sacramento");
        modelo_sacramentos.addColumn("Tipo");
        modelo_sacramentos.addColumn("Fecha");
        this.table_sacramentos_celebrados.setModel(modelo_sacramentos);
        //Tabla sacramentos celebrados
        modelo_actas.addColumn("Id");
        modelo_actas.addColumn("Tipo acta");
        modelo_actas.addColumn("Iglesia");
        modelo_actas.addColumn("Fecha expedición");
        this.table_actas_registradas.setModel(modelo_actas);
        
        //Insertar los datos en las tablas
        try {
            consultarTipos();
            consultarSacramentos();
            consultarActas();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("imagenes/Actas - white.png"));
        return retValue;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title_window = new javax.swing.JLabel();
        icon_window = new javax.swing.JLabel();
        id_acta_text = new javax.swing.JLabel();
        id_iglesia_text = new javax.swing.JLabel();
        id_tipo_text = new javax.swing.JLabel();
        id_sacramento_text = new javax.swing.JLabel();
        expedicion_acta_text = new javax.swing.JLabel();
        tipos_actas_text = new javax.swing.JLabel();
        sacramentos_celebrados_text = new javax.swing.JLabel();
        actas_registradas_text = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_refrescar_tablas = new javax.swing.JButton();
        id_acta_input = new javax.swing.JTextField();
        id_iglesia_input = new javax.swing.JTextField();
        id_tipo_input = new javax.swing.JTextField();
        id_sacramento_input = new javax.swing.JTextField();
        expedicion_acta_input = new javax.swing.JTextField();
        id_acta_separator = new javax.swing.JSeparator();
        id_iglesia_separator = new javax.swing.JSeparator();
        id_tipo_separator = new javax.swing.JSeparator();
        id_sacramento_separarator = new javax.swing.JSeparator();
        expedicion_acta_separator = new javax.swing.JSeparator();
        jScroll_table_1 = new javax.swing.JScrollPane();
        table_tipos_actas = new javax.swing.JTable();
        jScroll_table_2 = new javax.swing.JScrollPane();
        table_sacramentos_celebrados = new javax.swing.JTable();
        jScroll_table_3 = new javax.swing.JScrollPane();
        table_actas_registradas = new javax.swing.JTable();
        btn_rollback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actas");
        setIconImage(getIconImage());
        setResizable(false);

        background.setBackground(new java.awt.Color(237, 237, 237));
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        background.setPreferredSize(new java.awt.Dimension(985, 690));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_window.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        title_window.setForeground(new java.awt.Color(0, 0, 0));
        title_window.setText("Actas");
        background.add(title_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 43, -1, -1));

        icon_window.setIcon(icon_Actas);
        background.add(icon_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 43, 40, 40));

        id_acta_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_acta_text.setForeground(new java.awt.Color(0, 0, 0));
        id_acta_text.setText("Id acta");
        background.add(id_acta_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 151, -1, -1));

        id_iglesia_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_iglesia_text.setForeground(new java.awt.Color(0, 0, 0));
        id_iglesia_text.setText("Id iglesia");
        background.add(id_iglesia_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 214, -1, -1));

        id_tipo_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_tipo_text.setForeground(new java.awt.Color(0, 0, 0));
        id_tipo_text.setText("Id tipo");
        background.add(id_tipo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 277, -1, -1));

        id_sacramento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_text.setForeground(new java.awt.Color(0, 0, 0));
        id_sacramento_text.setText("Id sacramento");
        background.add(id_sacramento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 340, -1, -1));

        expedicion_acta_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        expedicion_acta_text.setForeground(new java.awt.Color(0, 0, 0));
        expedicion_acta_text.setText("Fecha expedición acta");
        background.add(expedicion_acta_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 402, -1, -1));

        tipos_actas_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        tipos_actas_text.setForeground(new java.awt.Color(0, 0, 0));
        tipos_actas_text.setText("Tipos de actas");
        background.add(tipos_actas_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 153, -1, -1));

        sacramentos_celebrados_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        sacramentos_celebrados_text.setForeground(new java.awt.Color(0, 0, 0));
        sacramentos_celebrados_text.setText("Sacramentos celebrados");
        background.add(sacramentos_celebrados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 153, -1, -1));

        actas_registradas_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        actas_registradas_text.setForeground(new java.awt.Color(0, 0, 0));
        actas_registradas_text.setText("Actas registradas");
        background.add(actas_registradas_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 340, -1, -1));

        btn_registrar.setBackground(new java.awt.Color(255, 192, 69));
        btn_registrar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.setFocusable(false);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        background.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 481, 266, 35));

        btn_refrescar_tablas.setBackground(new java.awt.Color(10, 145, 171));
        btn_refrescar_tablas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_refrescar_tablas.setForeground(new java.awt.Color(255, 255, 255));
        btn_refrescar_tablas.setText("Refrescar tablas");
        btn_refrescar_tablas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_refrescar_tablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refrescar_tablas.setFocusable(false);
        btn_refrescar_tablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseExited(evt);
            }
        });
        background.add(btn_refrescar_tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 539, 266, 35));

        id_acta_input.setBackground(new java.awt.Color(255, 255, 255));
        id_acta_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_acta_input.setForeground(new java.awt.Color(153, 51, 255));
        id_acta_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_acta_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 170, 266, 31));

        id_iglesia_input.setBackground(new java.awt.Color(255, 255, 255));
        id_iglesia_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_iglesia_input.setForeground(new java.awt.Color(153, 51, 255));
        id_iglesia_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_iglesia_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 233, 266, 31));

        id_tipo_input.setBackground(new java.awt.Color(255, 255, 255));
        id_tipo_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_tipo_input.setForeground(new java.awt.Color(153, 51, 255));
        id_tipo_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_tipo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 296, 266, 31));

        id_sacramento_input.setBackground(new java.awt.Color(255, 255, 255));
        id_sacramento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_input.setForeground(new java.awt.Color(153, 51, 255));
        id_sacramento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_sacramento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 359, 266, 31));

        expedicion_acta_input.setBackground(new java.awt.Color(255, 255, 255));
        expedicion_acta_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        expedicion_acta_input.setForeground(new java.awt.Color(153, 51, 255));
        expedicion_acta_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(expedicion_acta_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 421, 266, 31));

        id_acta_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_acta_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 201, 266, -1));

        id_iglesia_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_iglesia_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 264, 266, -1));

        id_tipo_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_tipo_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 327, 266, -1));

        id_sacramento_separarator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_sacramento_separarator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 390, 266, -1));

        expedicion_acta_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(expedicion_acta_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 452, 266, -1));

        table_tipos_actas.setBackground(new java.awt.Color(255, 255, 255));
        table_tipos_actas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_tipos_actas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id acta", "Nombre acta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_tipos_actas.setRowHeight(29);
        jScroll_table_1.setViewportView(table_tipos_actas);

        background.add(jScroll_table_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 180, 278, 144));

        table_sacramentos_celebrados.setBackground(new java.awt.Color(255, 255, 255));
        table_sacramentos_celebrados.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_sacramentos_celebrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id sacramento", "Tipo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_sacramentos_celebrados.setRowHeight(29);
        jScroll_table_2.setViewportView(table_sacramentos_celebrados);

        background.add(jScroll_table_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 278, 144));

        table_actas_registradas.setBackground(new java.awt.Color(255, 255, 255));
        table_actas_registradas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_actas_registradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo acta", "Iglesia", "Fecha expedición"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_actas_registradas.setRowHeight(29);
        jScroll_table_3.setViewportView(table_actas_registradas);

        background.add(jScroll_table_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 367, 573, 267));

        btn_rollback.setBackground(new java.awt.Color(10, 145, 171));
        btn_rollback.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_rollback.setForeground(new java.awt.Color(255, 255, 255));
        btn_rollback.setText("Ejecutar Rollback");
        btn_rollback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_rollback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rollback.setFocusable(false);
        btn_rollback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseExited(evt);
            }
        });
        background.add(btn_rollback, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 598, 266, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
        //Obtener los datos de los inputs
        String id_acta = id_acta_input.getText();
        String id_iglesia = id_iglesia_input.getText();
        String id_tipo = id_tipo_input.getText();
        String id_sacramento = id_sacramento_input.getText();
        String fecha_exp_acta = expedicion_acta_input.getText();
        
        if (id_acta.length() == 0 || id_iglesia.length() == 0 || id_tipo.length() == 0 ||
                id_sacramento.length() == 0 || fecha_exp_acta.length() == 0){
            config.setWarningMsg("Faltan por rellenar campos obligatorios!");
        } else {
            //Formatear los datos
            id_acta = "\'" + id_acta + "\'";
            id_iglesia = "\'" + id_iglesia + "\'";
            id_tipo = "\'" + id_tipo + "\'";
            id_sacramento = "\'" + id_sacramento + "\'";
            fecha_exp_acta = "\'" + fecha_exp_acta + "\'";
            //Agregamos el registro de la base de datos
            try {
                String sql = "begin; \n insert into acta values" +
                        "(" + id_acta + "," + id_iglesia + "," + id_tipo + "," + 
                        id_sacramento + "," + fecha_exp_acta + "); \n commit;";
                System.out.println(sql);
                java.sql.Statement statement = conexion.createStatement();
                statement.executeUpdate(sql);
            } catch (SQLException ex) {
                Configuraciones.setWarningMsg("" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_registrarMouseClicked

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
        btn_registrar.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        btn_registrar.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_registrarMouseExited

    private void btn_refrescar_tablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseClicked
        try {
            limpiarTabla(modelo_tipos);
            limpiarTabla(modelo_sacramentos);
            limpiarTabla(modelo_actas);
            consultarTipos();
            consultarSacramentos();
            consultarActas();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_refrescar_tablasMouseClicked

    private void btn_refrescar_tablasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseEntered
        btn_refrescar_tablas.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_refrescar_tablasMouseEntered

    private void btn_refrescar_tablasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseExited
        btn_refrescar_tablas.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_refrescar_tablasMouseExited

    private void btn_rollbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseClicked
        try {
            String sql = "rollback;";
            java.sql.Statement statement = conexion.createStatement();
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_rollbackMouseClicked

    private void btn_rollbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseEntered
        btn_rollback.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_rollbackMouseEntered

    private void btn_rollbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseExited
        btn_rollback.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_rollbackMouseExited
    
    public void consultarTipos() throws SQLException{
        try {
            String sql = " select id_tipo, nombre_tipo from tipo where id_tipo "
                    + "not in ('00001', '00002', '00003') order by id_tipo; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[2];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                modelo_tipos.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    public void consultarSacramentos() throws SQLException{
        try {
            String sql = " select id_sacramento , nombre_tipo, fecha_sacramento from sacramento "
                    + " inner join tipo on sacramento.id_tipo = tipo.id_tipo order by id_sacramento; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[3];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                modelo_sacramentos.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    public void consultarActas() throws SQLException{
        try {
            String sql = " select id_acta, tipo.nombre_tipo, nombre_iglesia, fecha_expedicion_acta from acta  "
                    + "inner join tipo on acta.id_tipo = tipo.id_tipo "
                    + "inner join iglesia on acta.id_iglesia = iglesia.id_iglesia "
                    + "inner join sacramento on acta.id_sacramento = sacramento.id_sacramento "
                    + "order by id_acta; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[5];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                modelo_actas.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    
    public void limpiarTabla(final DefaultTableModel model) {
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actas_registradas_text;
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_refrescar_tablas;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_rollback;
    private javax.swing.JTextField expedicion_acta_input;
    private javax.swing.JSeparator expedicion_acta_separator;
    private javax.swing.JLabel expedicion_acta_text;
    private javax.swing.JLabel icon_window;
    private javax.swing.JTextField id_acta_input;
    private javax.swing.JSeparator id_acta_separator;
    private javax.swing.JLabel id_acta_text;
    private javax.swing.JTextField id_iglesia_input;
    private javax.swing.JSeparator id_iglesia_separator;
    private javax.swing.JLabel id_iglesia_text;
    private javax.swing.JTextField id_sacramento_input;
    private javax.swing.JSeparator id_sacramento_separarator;
    private javax.swing.JLabel id_sacramento_text;
    private javax.swing.JTextField id_tipo_input;
    private javax.swing.JSeparator id_tipo_separator;
    private javax.swing.JLabel id_tipo_text;
    private javax.swing.JScrollPane jScroll_table_1;
    private javax.swing.JScrollPane jScroll_table_2;
    private javax.swing.JScrollPane jScroll_table_3;
    private javax.swing.JLabel sacramentos_celebrados_text;
    private javax.swing.JTable table_actas_registradas;
    private javax.swing.JTable table_sacramentos_celebrados;
    private javax.swing.JTable table_tipos_actas;
    private javax.swing.JLabel tipos_actas_text;
    private javax.swing.JLabel title_window;
    // End of variables declaration//GEN-END:variables
}
