package tramites_de_iglesia;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Feligreses extends javax.swing.JFrame {
    
    //Imagenes
    ImageIcon icon_Feligreses = new ImageIcon(ClassLoader.getSystemResource("imagenes/Feligreses.png"));
    ImageIcon icon_Info = new ImageIcon(ClassLoader.getSystemResource("imagenes/Info.png"));
    
    //Objetos
    Configuraciones config = new Configuraciones();
    
    String datos[] = config.leerArchivo(); //Leer los datos del archivo
    
    ConexionDB DB =  new ConexionDB();
    java.sql.Connection conexion = DB.conectarDB(DB.getDatabase(), datos[0], datos[1], false);
    
    DefaultTableModel modelo;
    /**
     * Creates new form Feligreses
     */
    public Feligreses() {
        initComponents();
        this.setLocationRelativeTo(null); //Centrar la ventana
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Id sexo");
        modelo.addColumn("DNI");
        modelo.addColumn("Id sacramento");
        modelo.addColumn("Fecha de nacimiento");
        this.table_feligreses.setModel(modelo);
        try {
            consultarTabla();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("imagenes/Feligreses - white.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroud = new javax.swing.JPanel();
        Title_window = new javax.swing.JLabel();
        id_feligres_text = new javax.swing.JLabel();
        id_sexo_text = new javax.swing.JLabel();
        id_perfil_educativo_text = new javax.swing.JLabel();
        id_perfil_parroquial_text = new javax.swing.JLabel();
        id_sacramento_text = new javax.swing.JLabel();
        dni_feligres_text = new javax.swing.JLabel();
        nombre_text = new javax.swing.JLabel();
        fecha_exp_dni_text = new javax.swing.JLabel();
        fecha_nacimiento_text = new javax.swing.JLabel();
        lug_nacimiento_text = new javax.swing.JLabel();
        direccion_text = new javax.swing.JLabel();
        foto_text = new javax.swing.JLabel();
        editar_feligres_text = new javax.swing.JLabel();
        borrar_feligres_text = new javax.swing.JLabel();
        id_feligres_input = new javax.swing.JTextField();
        id_sexo_input = new javax.swing.JTextField();
        id_perfil_educativo_input = new javax.swing.JTextField();
        id_perfil_parroquial_input = new javax.swing.JTextField();
        id_sacramento_input = new javax.swing.JTextField();
        dni_feligres_input = new javax.swing.JTextField();
        nombre_input = new javax.swing.JTextField();
        fecha_exp_dni_input = new javax.swing.JTextField();
        fecha_nacimiento_input = new javax.swing.JTextField();
        lugar_nacimiento_input = new javax.swing.JTextField();
        direccion_input = new javax.swing.JTextField();
        foto_input = new javax.swing.JTextField();
        id_feligres_separator = new javax.swing.JSeparator();
        id_sexo_separator = new javax.swing.JSeparator();
        id_perfil_educativo_separator = new javax.swing.JSeparator();
        id_perfil_parroquial_separator = new javax.swing.JSeparator();
        id_sacramento_separator = new javax.swing.JSeparator();
        dni_feligres_separator = new javax.swing.JSeparator();
        nombre_separator = new javax.swing.JSeparator();
        fecha_exp_dni_separator = new javax.swing.JSeparator();
        fecha_nacimiento_separartor = new javax.swing.JSeparator();
        lugar_nacimiento_separator = new javax.swing.JSeparator();
        direccion_separator = new javax.swing.JSeparator();
        foto_separator = new javax.swing.JSeparator();
        editar_feligres_input = new javax.swing.JTextField();
        borrar_feligres_input = new javax.swing.JTextField();
        editar_feligres_separator = new javax.swing.JSeparator();
        borrar_feligres_separator = new javax.swing.JSeparator();
        btn_registrar_actualizar = new javax.swing.JButton();
        btn_seleccionar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        icon_window = new javax.swing.JLabel();
        icon_info_window = new javax.swing.JLabel();
        registros_db_text = new javax.swing.JLabel();
        btn_refrescar = new javax.swing.JButton();
        jScroll_table = new javax.swing.JScrollPane();
        table_feligreses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Feligreses");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1285, 650));
        setResizable(false);

        Backgroud.setBackground(new java.awt.Color(237, 237, 237));
        Backgroud.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_window.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        Title_window.setForeground(new java.awt.Color(0, 0, 0));
        Title_window.setText("Feligreses");
        Backgroud.add(Title_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 43, -1, -1));

        id_feligres_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_feligres_text.setForeground(new java.awt.Color(0, 0, 0));
        id_feligres_text.setText("Id feligres");
        Backgroud.add(id_feligres_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 149, -1, -1));

        id_sexo_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sexo_text.setForeground(new java.awt.Color(0, 0, 0));
        id_sexo_text.setText("Id sexo");
        Backgroud.add(id_sexo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 149, -1, -1));

        id_perfil_educativo_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_perfil_educativo_text.setForeground(new java.awt.Color(0, 0, 0));
        id_perfil_educativo_text.setText("Id perfil educativo");
        Backgroud.add(id_perfil_educativo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 214, -1, -1));

        id_perfil_parroquial_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_perfil_parroquial_text.setForeground(new java.awt.Color(0, 0, 0));
        id_perfil_parroquial_text.setText("Id perfil parroquial");
        Backgroud.add(id_perfil_parroquial_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 214, -1, -1));

        id_sacramento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_text.setForeground(new java.awt.Color(0, 0, 0));
        id_sacramento_text.setText("Id sacramento");
        Backgroud.add(id_sacramento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 277, -1, -1));

        dni_feligres_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        dni_feligres_text.setForeground(new java.awt.Color(0, 0, 0));
        dni_feligres_text.setText("DNI feligres");
        Backgroud.add(dni_feligres_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 277, -1, -1));

        nombre_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        nombre_text.setForeground(new java.awt.Color(0, 0, 0));
        nombre_text.setText("Nombre");
        Backgroud.add(nombre_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 340, -1, -1));

        fecha_exp_dni_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_exp_dni_text.setForeground(new java.awt.Color(0, 0, 0));
        fecha_exp_dni_text.setText("Fecha de expedición DNI");
        Backgroud.add(fecha_exp_dni_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 340, -1, -1));

        fecha_nacimiento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_nacimiento_text.setForeground(new java.awt.Color(0, 0, 0));
        fecha_nacimiento_text.setText("Fecha de nacimiento");
        Backgroud.add(fecha_nacimiento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 403, -1, -1));

        lug_nacimiento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lug_nacimiento_text.setForeground(new java.awt.Color(0, 0, 0));
        lug_nacimiento_text.setText("Lugar de nacimiento");
        Backgroud.add(lug_nacimiento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 403, -1, -1));

        direccion_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        direccion_text.setForeground(new java.awt.Color(0, 0, 0));
        direccion_text.setText("Dirección");
        Backgroud.add(direccion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 466, -1, -1));

        foto_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        foto_text.setForeground(new java.awt.Color(0, 0, 0));
        foto_text.setText("Foto");
        Backgroud.add(foto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 466, -1, -1));

        editar_feligres_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        editar_feligres_text.setForeground(new java.awt.Color(0, 0, 0));
        editar_feligres_text.setText("Editar feligres");
        Backgroud.add(editar_feligres_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 147, -1, -1));

        borrar_feligres_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        borrar_feligres_text.setForeground(new java.awt.Color(0, 0, 0));
        borrar_feligres_text.setText("Borrar feligres");
        Backgroud.add(borrar_feligres_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 147, -1, -1));

        id_feligres_input.setBackground(new java.awt.Color(255, 255, 255));
        id_feligres_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_feligres_input.setForeground(new java.awt.Color(153, 51, 255));
        id_feligres_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(id_feligres_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 170, 266, 31));

        id_sexo_input.setBackground(new java.awt.Color(255, 255, 255));
        id_sexo_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sexo_input.setForeground(new java.awt.Color(153, 51, 255));
        id_sexo_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(id_sexo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 170, 266, 31));

        id_perfil_educativo_input.setBackground(new java.awt.Color(255, 255, 255));
        id_perfil_educativo_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_perfil_educativo_input.setForeground(new java.awt.Color(153, 51, 255));
        id_perfil_educativo_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(id_perfil_educativo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 233, 266, 31));

        id_perfil_parroquial_input.setBackground(new java.awt.Color(255, 255, 255));
        id_perfil_parroquial_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_perfil_parroquial_input.setForeground(new java.awt.Color(153, 51, 255));
        id_perfil_parroquial_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(id_perfil_parroquial_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 233, 266, 31));

        id_sacramento_input.setBackground(new java.awt.Color(255, 255, 255));
        id_sacramento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_input.setForeground(new java.awt.Color(153, 51, 255));
        id_sacramento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(id_sacramento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 296, 266, 31));

        dni_feligres_input.setBackground(new java.awt.Color(255, 255, 255));
        dni_feligres_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        dni_feligres_input.setForeground(new java.awt.Color(153, 51, 255));
        dni_feligres_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(dni_feligres_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 296, 266, 31));

        nombre_input.setBackground(new java.awt.Color(255, 255, 255));
        nombre_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        nombre_input.setForeground(new java.awt.Color(153, 51, 255));
        nombre_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(nombre_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 359, 266, 31));

        fecha_exp_dni_input.setBackground(new java.awt.Color(255, 255, 255));
        fecha_exp_dni_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_exp_dni_input.setForeground(new java.awt.Color(153, 51, 255));
        fecha_exp_dni_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(fecha_exp_dni_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 359, 266, 31));

        fecha_nacimiento_input.setBackground(new java.awt.Color(255, 255, 255));
        fecha_nacimiento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_nacimiento_input.setForeground(new java.awt.Color(153, 51, 255));
        fecha_nacimiento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(fecha_nacimiento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 422, 266, 31));

        lugar_nacimiento_input.setBackground(new java.awt.Color(255, 255, 255));
        lugar_nacimiento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        lugar_nacimiento_input.setForeground(new java.awt.Color(153, 51, 255));
        lugar_nacimiento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(lugar_nacimiento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 422, 266, 31));

        direccion_input.setBackground(new java.awt.Color(255, 255, 255));
        direccion_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        direccion_input.setForeground(new java.awt.Color(153, 51, 255));
        direccion_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(direccion_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 485, 266, 31));

        foto_input.setBackground(new java.awt.Color(255, 255, 255));
        foto_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        foto_input.setForeground(new java.awt.Color(153, 51, 255));
        foto_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(foto_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 485, 266, 31));

        id_feligres_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(id_feligres_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 201, 266, -1));

        id_sexo_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(id_sexo_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 201, 266, -1));

        id_perfil_educativo_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(id_perfil_educativo_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 264, 266, -1));

        id_perfil_parroquial_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(id_perfil_parroquial_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 264, 266, -1));

        id_sacramento_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(id_sacramento_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 327, 266, -1));

        dni_feligres_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(dni_feligres_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 327, 266, -1));

        nombre_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(nombre_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 390, 266, -1));

        fecha_exp_dni_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(fecha_exp_dni_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 390, 266, -1));

        fecha_nacimiento_separartor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(fecha_nacimiento_separartor, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 453, 266, -1));

        lugar_nacimiento_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(lugar_nacimiento_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 453, 266, -1));

        direccion_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(direccion_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 516, 266, -1));

        foto_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(foto_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 516, 266, -1));

        editar_feligres_input.setBackground(new java.awt.Color(255, 255, 255));
        editar_feligres_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        editar_feligres_input.setForeground(new java.awt.Color(153, 51, 255));
        editar_feligres_input.setText("Digite el id");
        editar_feligres_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(editar_feligres_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 170, 130, 31));

        borrar_feligres_input.setBackground(new java.awt.Color(255, 255, 255));
        borrar_feligres_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        borrar_feligres_input.setForeground(new java.awt.Color(153, 51, 255));
        borrar_feligres_input.setText("Digite el id");
        borrar_feligres_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Backgroud.add(borrar_feligres_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 170, 130, 31));

        editar_feligres_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(editar_feligres_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 201, 130, -1));

        borrar_feligres_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Backgroud.add(borrar_feligres_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 201, 130, -1));

        btn_registrar_actualizar.setBackground(new java.awt.Color(255, 192, 69));
        btn_registrar_actualizar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_registrar_actualizar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar_actualizar.setText("Registrar / Actualizar");
        btn_registrar_actualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_registrar_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar_actualizar.setFocusable(false);
        btn_registrar_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrar_actualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrar_actualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrar_actualizarMouseExited(evt);
            }
        });
        Backgroud.add(btn_registrar_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 545, 266, 35));

        btn_seleccionar.setBackground(new java.awt.Color(10, 145, 171));
        btn_seleccionar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_seleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btn_seleccionar.setText("Seleccionar");
        btn_seleccionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_seleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_seleccionar.setFocusable(false);
        btn_seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_seleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_seleccionarMouseExited(evt);
            }
        });
        Backgroud.add(btn_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 168, 130, 35));

        btn_eliminar.setBackground(new java.awt.Color(10, 145, 171));
        btn_eliminar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setFocusable(false);
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseExited(evt);
            }
        });
        Backgroud.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 168, 130, 35));

        icon_window.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon_window.setIcon(icon_Feligreses);
        Backgroud.add(icon_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 43, 40, 40));

        icon_info_window.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon_info_window.setIcon(icon_Info);
        Backgroud.add(icon_info_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 60, 16, 16));

        registros_db_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        registros_db_text.setForeground(new java.awt.Color(0, 0, 0));
        registros_db_text.setText("Registros de la Base de Datos");
        Backgroud.add(registros_db_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 237, -1, -1));

        btn_refrescar.setBackground(new java.awt.Color(10, 145, 171));
        btn_refrescar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_refrescar.setForeground(new java.awt.Color(255, 255, 255));
        btn_refrescar.setText("Refrescar tabla");
        btn_refrescar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_refrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refrescar.setFocusable(false);
        btn_refrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refrescarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refrescarMouseExited(evt);
            }
        });
        btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrescarActionPerformed(evt);
            }
        });
        Backgroud.add(btn_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 545, 266, 35));

        table_feligreses.setBackground(new java.awt.Color(255, 255, 255));
        table_feligreses.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_feligreses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Id sexo", "DNI", "Id sacramento", "Fecha de nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_feligreses.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table_feligreses.setOpaque(false);
        table_feligreses.setRowHeight(29);
        table_feligreses.setShowGrid(true);
        jScroll_table.setViewportView(table_feligreses);
        if (table_feligreses.getColumnModel().getColumnCount() > 0) {
            table_feligreses.getColumnModel().getColumn(5).setPreferredWidth(125);
        }

        Backgroud.add(jScroll_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 264, 573, 252));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refrescarActionPerformed

    private void btn_registrar_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_actualizarMouseClicked
        //Obtener los datos de los inputs
        String id_feligres = id_feligres_input.getText();
        String id_sexo = id_sexo_input.getText();
        String id_perfil_educativo = id_perfil_educativo_input.getText();
        String id_perfil_parroquial = id_perfil_parroquial_input.getText();
        String id_sacramento = id_sacramento_input.getText();
        String dni_feligres = dni_feligres_input.getText();
        String nombre = nombre_input.getText();
        String fecha_expedicion_dni = fecha_exp_dni_input.getText();
        String fecha_nacimiento = fecha_nacimiento_input.getText();
        String lugar_nacimiento = lugar_nacimiento_input.getText();
        String direccion = direccion_input.getText();
        String foto = foto_input.getText();
        
        //Buscar el id
        String idEncontrado = buscarId(id_feligres);
        
        //Formatear datos
        if (id_sacramento.length() == 0 || dni_feligres.length() == 0 || nombre.length() == 0){
            config.setWarningMsg("Faltan por rellenar campos obligatorios!");
        } else {
            //Formatear los datos
            id_feligres = formatearValor(id_feligres);
            id_sexo = formatearValor(id_sexo);
            id_perfil_educativo = formatearValor(id_perfil_educativo);
            id_perfil_parroquial = formatearValor(id_perfil_parroquial);
            id_sacramento = formatearValor(id_sacramento);
            dni_feligres = formatearValor(dni_feligres);
            nombre = formatearValor(nombre);
            fecha_expedicion_dni = formatearValor(fecha_expedicion_dni);
            fecha_nacimiento = formatearValor(fecha_nacimiento);
            lugar_nacimiento = formatearValor(lugar_nacimiento);
            direccion = formatearValor(direccion);
            foto = formatearValor(foto);
            if (idEncontrado == "0"){ //El id no existe en la Base de Datos
                //Insertar los datos en la DB
                try {
                    String sql = "insert into feligreses values" +
                            "(" + id_feligres + "," + id_perfil_educativo + "," + id_sexo + "," + 
                            id_perfil_parroquial + "," + id_sacramento + "," + dni_feligres + "," + nombre + "," + 
                            fecha_nacimiento + "," + lugar_nacimiento + "," + direccion + "," + 
                            fecha_expedicion_dni + "," + foto + ");";
                    java.sql.Statement statement = conexion.createStatement();
                    statement.executeUpdate(sql);
                } catch (SQLException ex) {
                    Configuraciones.setWarningMsg("" + ex.getMessage());
                }
            } else { //El id existe en la Base de Datos
                //Actualizamos el registro de la base de datos
                try {
                    String sql = "update feligreses set " +
                        "id_perfil_educativo = " + id_perfil_educativo + ", id_sexo = " + id_sexo + ", " + 
                        "id_perfil_parroquial = " + id_perfil_parroquial + ", id_sacramento = " + id_sacramento + ", " +
                        "dni_feligres = " + dni_feligres + ", nombre_feligres = " + nombre + ", " +
                        "fecha_nacimiento_feligres = " + fecha_nacimiento + ", " +
                        "lugar_nacimiento_feligres = " + lugar_nacimiento + ", " +
                        "direccion_feligres = " + direccion + ", fecha_expedicion_dni = " + fecha_expedicion_dni + ", " +
                        "foto_feligres = " + foto + " where id_feligres = " + id_feligres + ";";
                    java.sql.Statement statement = conexion.createStatement();
                    statement.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Feligres actualizado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Configuraciones.setWarningMsg("" + ex.getMessage());
                }
            }
            
        }
    }//GEN-LAST:event_btn_registrar_actualizarMouseClicked

    private void btn_seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarMouseClicked
        String id_feligres_editar = editar_feligres_input.getText();
        String idEncontrado = buscarId(id_feligres_editar);
        if (idEncontrado.equals("Digite el id")){ //En caso de presionar el botón sin cambiar los datos del input
        } else {
            if(idEncontrado != "0"){
                try {
                    String sql = "select * from feligreses where id_feligres = \'" + idEncontrado + "\';"; 
                    java.sql.Statement statement = conexion.createStatement();
                    ResultSet rs = statement.executeQuery(sql);

                    while (rs.next()){ //Extraemos el resultado de la consulta
                        id_feligres_input.setText(rs.getString(1));
                        id_perfil_educativo_input.setText(rs.getString(2));
                        id_sexo_input.setText(rs.getString(3));
                        id_perfil_parroquial_input.setText(rs.getString(4));
                        id_sacramento_input.setText(rs.getString(5));
                        dni_feligres_input.setText(rs.getString(6));
                        nombre_input.setText(rs.getString(7));
                        fecha_nacimiento_input.setText(rs.getString(8));
                        lugar_nacimiento_input.setText(rs.getString(9));
                        direccion_input.setText(rs.getString(10));
                        fecha_exp_dni_input.setText(rs.getString(11));
                        foto_input.setText(rs.getString(12));
                    }
                } catch (SQLException ex) {
                    Configuraciones.setWarningMsg("" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_seleccionarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        String id_feligres_eliminar = borrar_feligres_input.getText();
        String idEncontrado = buscarId(id_feligres_eliminar);
        if (idEncontrado.equals("Digite el id")){ //En caso de presionar el botón sin cambiar los datos del input
        } else {
            if(idEncontrado != "0"){
                try {
                    int resultado = JOptionPane.showConfirmDialog(null,
                            "¿Desea eliminar el feligres con el Id: " + idEncontrado + "?", "Confirmar eliminación",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if(resultado == JOptionPane.YES_OPTION){
                        String sql = "delete from feligreses where id_feligres = " + "\'" + idEncontrado + "\'";
                        java.sql.Statement statement = conexion.createStatement();
                        statement.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Feligres eliminado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Configuraciones.setWarningMsg("" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_refrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescarMouseClicked
        try {
            limpiarTabla(modelo);
            consultarTabla();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_refrescarMouseClicked

    private void btn_registrar_actualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_actualizarMouseEntered
        btn_registrar_actualizar.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_registrar_actualizarMouseEntered

    private void btn_registrar_actualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrar_actualizarMouseExited
        btn_registrar_actualizar.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_registrar_actualizarMouseExited

    private void btn_seleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarMouseEntered
        btn_seleccionar.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_seleccionarMouseEntered

    private void btn_seleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seleccionarMouseExited
        btn_seleccionar.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_seleccionarMouseExited

    private void btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseEntered
        btn_eliminar.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_eliminarMouseEntered

    private void btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseExited
        btn_eliminar.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_eliminarMouseExited

    private void btn_refrescarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescarMouseEntered
        btn_refrescar.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_refrescarMouseEntered

    private void btn_refrescarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescarMouseExited
        btn_refrescar.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_refrescarMouseExited
    
    public String formatearValor(String dato){
        if(dato.length() > 0){
            dato = "\'" + dato + "\'";
        } else {
            dato = "null";
        }
        return dato;
    }
    
    public String buscarId(String id){
        if(id.length() > 0){
            try {
                String sql = "select count(id_feligres) from feligreses where id_feligres = \'" + id + "\';"; 
                java.sql.Statement statement = conexion.createStatement();
                ResultSet rs = statement.executeQuery(sql);
                
                int found = 0; //Almacena 1 si encentra el id y 0 en caso contrario.
                while (rs.next()){ //Extraemos el resultado de la consulta (en columnas)
                    found = rs.getInt(1); //Accedemos a la columna y asignamos el valor a una nueva variable
                }
                if(found >= 1){ //Verificamos el valor de la variable (1 o 0)
                    //JOptionPane.showMessageDialog(null, "Id encontrado!");
                } else {
                    id = "0";
                    JOptionPane.showMessageDialog(null, "Id no encontrado!");
                }
            } catch (SQLException ex) {
                Configuraciones.setWarningMsg("" + ex.getMessage());
            }
        } else {
             Configuraciones.setWarningMsg("No hay id para seleccionar!");
        }
        return id;
    }
    
    public void consultarTabla() throws SQLException{
        try {
            String sql = " select id_feligres, nombre_feligres, id_sexo, dni_feligres, " +
                         " id_sacramento, fecha_nacimiento_feligres from feligreses " +
                         " order by id_feligres; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[6];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);
                filas[5] = rs.getString(6);
                modelo.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    
    public void limpiarTabla(final DefaultTableModel model) {
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feligreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feligreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feligreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feligreses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feligreses().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroud;
    private javax.swing.JLabel Title_window;
    private javax.swing.JTextField borrar_feligres_input;
    private javax.swing.JSeparator borrar_feligres_separator;
    private javax.swing.JLabel borrar_feligres_text;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_refrescar;
    private javax.swing.JButton btn_registrar_actualizar;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JTextField direccion_input;
    private javax.swing.JSeparator direccion_separator;
    private javax.swing.JLabel direccion_text;
    private javax.swing.JTextField dni_feligres_input;
    private javax.swing.JSeparator dni_feligres_separator;
    private javax.swing.JLabel dni_feligres_text;
    private javax.swing.JTextField editar_feligres_input;
    private javax.swing.JSeparator editar_feligres_separator;
    private javax.swing.JLabel editar_feligres_text;
    private javax.swing.JTextField fecha_exp_dni_input;
    private javax.swing.JSeparator fecha_exp_dni_separator;
    private javax.swing.JLabel fecha_exp_dni_text;
    private javax.swing.JTextField fecha_nacimiento_input;
    private javax.swing.JSeparator fecha_nacimiento_separartor;
    private javax.swing.JLabel fecha_nacimiento_text;
    private javax.swing.JTextField foto_input;
    private javax.swing.JSeparator foto_separator;
    private javax.swing.JLabel foto_text;
    private javax.swing.JLabel icon_info_window;
    private javax.swing.JLabel icon_window;
    private javax.swing.JTextField id_feligres_input;
    private javax.swing.JSeparator id_feligres_separator;
    private javax.swing.JLabel id_feligres_text;
    private javax.swing.JTextField id_perfil_educativo_input;
    private javax.swing.JSeparator id_perfil_educativo_separator;
    private javax.swing.JLabel id_perfil_educativo_text;
    private javax.swing.JTextField id_perfil_parroquial_input;
    private javax.swing.JSeparator id_perfil_parroquial_separator;
    private javax.swing.JLabel id_perfil_parroquial_text;
    private javax.swing.JTextField id_sacramento_input;
    private javax.swing.JSeparator id_sacramento_separator;
    private javax.swing.JLabel id_sacramento_text;
    private javax.swing.JTextField id_sexo_input;
    private javax.swing.JSeparator id_sexo_separator;
    private javax.swing.JLabel id_sexo_text;
    private javax.swing.JScrollPane jScroll_table;
    private javax.swing.JLabel lug_nacimiento_text;
    private javax.swing.JTextField lugar_nacimiento_input;
    private javax.swing.JSeparator lugar_nacimiento_separator;
    private javax.swing.JTextField nombre_input;
    private javax.swing.JSeparator nombre_separator;
    private javax.swing.JLabel nombre_text;
    private javax.swing.JLabel registros_db_text;
    private javax.swing.JTable table_feligreses;
    // End of variables declaration//GEN-END:variables
}
