package tramites_de_iglesia;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

public class Panel extends javax.swing.JFrame {

    //Objetos
    Configuraciones config = new Configuraciones();
    Feligreses feligreses = new Feligreses();
    Padres padres = new Padres();
    Sacramentos sacramentos = new Sacramentos();
    Actas actas = new Actas();
    
    //Imagenes
    ImageIcon icon_Feligreses = new ImageIcon(ClassLoader.getSystemResource("imagenes/Feligreses.png"));
    ImageIcon icon_Padres = new ImageIcon(ClassLoader.getSystemResource("imagenes/Padres.png"));
    ImageIcon icon_Sacramentos = new ImageIcon(ClassLoader.getSystemResource("imagenes/Sacramentos.png"));
    ImageIcon icon_Actas = new ImageIcon(ClassLoader.getSystemResource("imagenes/Actas.png"));
    
    public Panel() {
        initComponents();
        this.setLocationRelativeTo(null); //Centrar ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        title_window = new javax.swing.JLabel();
        crud_text = new javax.swing.JLabel();
        transacciones_text = new javax.swing.JLabel();
        btn_feligreses = new javax.swing.JButton();
        btn_padres = new javax.swing.JButton();
        btn_sacramentos = new javax.swing.JButton();
        btn_actas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de control");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setResizable(false);

        Background.setBackground(new java.awt.Color(237, 237, 237));
        Background.setMaximumSize(new java.awt.Dimension(680, 490));
        Background.setMinimumSize(new java.awt.Dimension(680, 490));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_window.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        title_window.setForeground(new java.awt.Color(0, 0, 0));
        title_window.setText("Panel de control");
        Background.add(title_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 43, -1, -1));

        crud_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        crud_text.setForeground(new java.awt.Color(0, 0, 0));
        crud_text.setText("CRUD");
        Background.add(crud_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 148, -1, -1));

        transacciones_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        transacciones_text.setForeground(new java.awt.Color(0, 0, 0));
        transacciones_text.setText("Transacciones");
        Background.add(transacciones_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 148, -1, -1));

        btn_feligreses.setBackground(new java.awt.Color(255, 192, 69));
        btn_feligreses.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btn_feligreses.setForeground(new java.awt.Color(0, 0, 0));
        btn_feligreses.setIcon(icon_Feligreses);
        btn_feligreses.setText("Feligreses");
        btn_feligreses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_feligreses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_feligreses.setFocusable(false);
        btn_feligreses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_feligreses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_feligreses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_feligresesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_feligresesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_feligresesMouseExited(evt);
            }
        });
        btn_feligreses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feligresesActionPerformed(evt);
            }
        });
        Background.add(btn_feligreses, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 191, 125, 125));

        btn_padres.setBackground(new java.awt.Color(255, 192, 69));
        btn_padres.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btn_padres.setForeground(new java.awt.Color(0, 0, 0));
        btn_padres.setIcon(icon_Padres);
        btn_padres.setText("Padres");
        btn_padres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_padres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_padres.setFocusable(false);
        btn_padres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_padres.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_padres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_padresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_padresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_padresMouseExited(evt);
            }
        });
        Background.add(btn_padres, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 191, 125, 125));

        btn_sacramentos.setBackground(new java.awt.Color(255, 192, 69));
        btn_sacramentos.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btn_sacramentos.setForeground(new java.awt.Color(0, 0, 0));
        btn_sacramentos.setIcon(icon_Sacramentos);
        btn_sacramentos.setText("Sacramentos");
        btn_sacramentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_sacramentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sacramentos.setFocusable(false);
        btn_sacramentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_sacramentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sacramentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sacramentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sacramentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sacramentosMouseExited(evt);
            }
        });
        Background.add(btn_sacramentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 191, 125, 125));

        btn_actas.setBackground(new java.awt.Color(255, 192, 69));
        btn_actas.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btn_actas.setForeground(new java.awt.Color(0, 0, 0));
        btn_actas.setIcon(icon_Actas);
        btn_actas.setText("Actas");
        btn_actas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_actas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actas.setFocusable(false);
        btn_actas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_actas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_actas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_actasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_actasMouseExited(evt);
            }
        });
        Background.add(btn_actas, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 191, 125, 125));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_feligresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feligresesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_feligresesActionPerformed

    private void btn_feligresesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feligresesMouseClicked
        feligreses.setVisible(true);
    }//GEN-LAST:event_btn_feligresesMouseClicked

    private void btn_padresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_padresMouseClicked
        padres.setVisible(true);
    }//GEN-LAST:event_btn_padresMouseClicked

    private void btn_sacramentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sacramentosMouseClicked
        sacramentos.setVisible(true);
    }//GEN-LAST:event_btn_sacramentosMouseClicked

    private void btn_actasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actasMouseClicked
        actas.setVisible(true);
    }//GEN-LAST:event_btn_actasMouseClicked

    private void btn_feligresesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feligresesMouseEntered
        btn_feligreses.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_feligresesMouseEntered

    private void btn_feligresesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_feligresesMouseExited
        btn_feligreses.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_feligresesMouseExited

    private void btn_padresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_padresMouseEntered
       btn_padres.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_padresMouseEntered

    private void btn_padresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_padresMouseExited
        btn_padres.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_padresMouseExited

    private void btn_sacramentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sacramentosMouseEntered
        btn_sacramentos.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_sacramentosMouseEntered

    private void btn_sacramentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sacramentosMouseExited
        btn_sacramentos.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_sacramentosMouseExited

    private void btn_actasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actasMouseEntered
        btn_actas.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_actasMouseEntered

    private void btn_actasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actasMouseExited
        btn_actas.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_actasMouseExited
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("imagenes/Panel de control - white.png"));
        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btn_actas;
    private javax.swing.JButton btn_feligreses;
    private javax.swing.JButton btn_padres;
    private javax.swing.JButton btn_sacramentos;
    private javax.swing.JLabel crud_text;
    private javax.swing.JLabel title_window;
    private javax.swing.JLabel transacciones_text;
    // End of variables declaration//GEN-END:variables
}
