package tramites_de_iglesia;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Sacramentos extends javax.swing.JFrame {

    //Imagenes
    ImageIcon icon_Sacramentos = new ImageIcon(ClassLoader.getSystemResource("imagenes/Sacramentos.png"));
    
    //Objetos
    Configuraciones config = new Configuraciones();
    
    String datos[] = config.leerArchivo(); //Leer los datos del archivo
    
    ConexionDB DB =  new ConexionDB();
    java.sql.Connection conexion = DB.conectarDB(DB.getDatabase(), datos[0], datos[1], false);
    
    //Modelos para las tablas
    DefaultTableModel modelo_sacerdotes;
    DefaultTableModel modelo_tipos;
    DefaultTableModel modelo_sacramentos;
    
    /**
     * Creates new form Sacramentos
     */
    public Sacramentos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Definir los modelos
        modelo_sacerdotes = new DefaultTableModel();
        modelo_tipos = new DefaultTableModel();
        modelo_sacramentos = new DefaultTableModel();
        
        //Tabla sacerdotes
        modelo_sacerdotes.addColumn("Id sacerdote");
        modelo_sacerdotes.addColumn("Nombre sacerdote");
        this.table_sacerdotes.setModel(modelo_sacerdotes);
        //Tabla tipos de sacramentos
        modelo_tipos.addColumn("Id tipo");
        modelo_tipos.addColumn("Nombre tipo");
        this.table_tipos_sacramentos.setModel(modelo_tipos);
        //Tabla sacramentos celebrados
        modelo_sacramentos.addColumn("Id");
        modelo_sacramentos.addColumn("Sacerdote");
        modelo_sacramentos.addColumn("Tipo");
        modelo_sacramentos.addColumn("Fecha sacramento");
        this.table_sacramentos_celebrados.setModel(modelo_sacramentos);
        
        //Insertar los datos en las tablas
        try {
            consultarSacerdotes();
            consultarTipos();
            consultarSacramentos();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("imagenes/Sacramentos - white.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title_window = new javax.swing.JLabel();
        icon_window = new javax.swing.JLabel();
        id_sacramento_text = new javax.swing.JLabel();
        id_sacerdote_text = new javax.swing.JLabel();
        id_tipo_text = new javax.swing.JLabel();
        fecha_sacramento_text = new javax.swing.JLabel();
        sacerdotes_text = new javax.swing.JLabel();
        tipos_sacramentos_text = new javax.swing.JLabel();
        sacramentos_celebrados_text = new javax.swing.JLabel();
        id_sacramento_input = new javax.swing.JTextField();
        id_sacerdote_input = new javax.swing.JTextField();
        id_tipo_input = new javax.swing.JTextField();
        fecha_sacramento_input = new javax.swing.JTextField();
        id_sacramento_separator = new javax.swing.JSeparator();
        id_sacerdote_separator = new javax.swing.JSeparator();
        id_tipo_separator = new javax.swing.JSeparator();
        fecha_sacramento_separator = new javax.swing.JSeparator();
        btn_registrar = new javax.swing.JButton();
        btn_refrescar_tablas = new javax.swing.JButton();
        jScroll_table_1 = new javax.swing.JScrollPane();
        table_sacerdotes = new javax.swing.JTable();
        jScroll_table_2 = new javax.swing.JScrollPane();
        table_tipos_sacramentos = new javax.swing.JTable();
        jScroll_table_3 = new javax.swing.JScrollPane();
        table_sacramentos_celebrados = new javax.swing.JTable();
        btn_rollback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sacramentos");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(985, 625));
        setResizable(false);

        background.setBackground(new java.awt.Color(237, 237, 237));
        background.setMinimumSize(new java.awt.Dimension(985, 625));
        background.setPreferredSize(new java.awt.Dimension(985, 625));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_window.setFont(new java.awt.Font("Roboto", 1, 40)); // NOI18N
        title_window.setForeground(new java.awt.Color(0, 0, 0));
        title_window.setText("Sacramentos");
        background.add(title_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 43, -1, -1));

        icon_window.setForeground(new java.awt.Color(0, 0, 0));
        icon_window.setIcon(icon_Sacramentos);
        background.add(icon_window, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 43, 40, 40));

        id_sacramento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_text.setForeground(new java.awt.Color(0, 0, 0));
        id_sacramento_text.setText("Id sacramento");
        background.add(id_sacramento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 151, -1, -1));

        id_sacerdote_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacerdote_text.setForeground(new java.awt.Color(0, 0, 0));
        id_sacerdote_text.setText("Id sacerdote");
        background.add(id_sacerdote_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 214, -1, -1));

        id_tipo_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_tipo_text.setForeground(new java.awt.Color(0, 0, 0));
        id_tipo_text.setText("Id tipo");
        background.add(id_tipo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 277, -1, -1));

        fecha_sacramento_text.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_sacramento_text.setForeground(new java.awt.Color(0, 0, 0));
        fecha_sacramento_text.setText("Fecha sacramento");
        background.add(fecha_sacramento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 340, -1, -1));

        sacerdotes_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        sacerdotes_text.setForeground(new java.awt.Color(0, 0, 0));
        sacerdotes_text.setText("Sacerdotes");
        background.add(sacerdotes_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 153, -1, -1));

        tipos_sacramentos_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        tipos_sacramentos_text.setForeground(new java.awt.Color(0, 0, 0));
        tipos_sacramentos_text.setText("Tipos de sacramentos");
        background.add(tipos_sacramentos_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 153, -1, -1));

        sacramentos_celebrados_text.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        sacramentos_celebrados_text.setForeground(new java.awt.Color(0, 0, 0));
        sacramentos_celebrados_text.setText("Sacramentos celebrados");
        background.add(sacramentos_celebrados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 340, -1, -1));

        id_sacramento_input.setBackground(new java.awt.Color(255, 255, 255));
        id_sacramento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacramento_input.setForeground(new java.awt.Color(153, 51, 255));
        id_sacramento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_sacramento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 170, 266, 31));

        id_sacerdote_input.setBackground(new java.awt.Color(255, 255, 255));
        id_sacerdote_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_sacerdote_input.setForeground(new java.awt.Color(153, 51, 255));
        id_sacerdote_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_sacerdote_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 233, 266, 31));

        id_tipo_input.setBackground(new java.awt.Color(255, 255, 255));
        id_tipo_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        id_tipo_input.setForeground(new java.awt.Color(153, 51, 255));
        id_tipo_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(id_tipo_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 296, 266, 31));

        fecha_sacramento_input.setBackground(new java.awt.Color(255, 255, 255));
        fecha_sacramento_input.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        fecha_sacramento_input.setForeground(new java.awt.Color(153, 51, 255));
        fecha_sacramento_input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        background.add(fecha_sacramento_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 359, 266, 31));

        id_sacramento_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_sacramento_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 201, 266, -1));

        id_sacerdote_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_sacerdote_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 264, 266, -1));

        id_tipo_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(id_tipo_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 327, 266, -1));

        fecha_sacramento_separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        background.add(fecha_sacramento_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 390, 266, -1));

        btn_registrar.setBackground(new java.awt.Color(255, 192, 69));
        btn_registrar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 117, 0), 2, true));
        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.setFocusable(false);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });
        background.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 419, 266, 35));

        btn_refrescar_tablas.setBackground(new java.awt.Color(10, 145, 171));
        btn_refrescar_tablas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_refrescar_tablas.setForeground(new java.awt.Color(255, 255, 255));
        btn_refrescar_tablas.setText("Refrescar tablas");
        btn_refrescar_tablas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_refrescar_tablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refrescar_tablas.setFocusable(false);
        btn_refrescar_tablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_refrescar_tablasMouseExited(evt);
            }
        });
        background.add(btn_refrescar_tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 477, 266, 35));

        table_sacerdotes.setBackground(new java.awt.Color(255, 255, 255));
        table_sacerdotes.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_sacerdotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id sacerdote", "Nombre sacerdote"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_sacerdotes.setRowHeight(29);
        jScroll_table_1.setViewportView(table_sacerdotes);

        background.add(jScroll_table_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 180, 278, 144));

        table_tipos_sacramentos.setBackground(new java.awt.Color(255, 255, 255));
        table_tipos_sacramentos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_tipos_sacramentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id tipo", "Nombre tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_tipos_sacramentos.setRowHeight(29);
        jScroll_table_2.setViewportView(table_tipos_sacramentos);

        background.add(jScroll_table_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 278, 144));

        table_sacramentos_celebrados.setBackground(new java.awt.Color(255, 255, 255));
        table_sacramentos_celebrados.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        table_sacramentos_celebrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Tipo", "Fecha sacramento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_sacramentos_celebrados.setRowHeight(29);
        jScroll_table_3.setViewportView(table_sacramentos_celebrados);

        background.add(jScroll_table_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 367, 573, 205));

        btn_rollback.setBackground(new java.awt.Color(10, 145, 171));
        btn_rollback.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_rollback.setForeground(new java.awt.Color(255, 255, 255));
        btn_rollback.setText("Ejecutar Rollback");
        btn_rollback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 84, 113), 2, true));
        btn_rollback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rollback.setFocusable(false);
        btn_rollback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_rollbackMouseExited(evt);
            }
        });
        background.add(btn_rollback, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 536, 266, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseClicked
        //Obtener los datos de los inputs
        String id_sacramento = id_sacramento_input.getText();
        String id_sacerdote = id_sacerdote_input.getText();
        String id_tipo = id_tipo_input.getText();
        String fecha_sacramento = fecha_sacramento_input.getText();
        
        if (id_sacramento.length() == 0 || id_sacerdote.length() == 0 ||
                id_tipo.length() == 0 || fecha_sacramento.length() == 0){
            config.setWarningMsg("Faltan por rellenar campos obligatorios!");
        } else {
            //Formatear los datos
            id_sacramento = "\'" + id_sacramento + "\'";
            id_sacerdote = "\'" + id_sacerdote + "\'";
            id_tipo = "\'" + id_tipo + "\'";
            fecha_sacramento = "\'" + fecha_sacramento + "\'";
            //Agregamos el registro de la base de datos
            try {
                String sql = "begin; \n insert into sacramento values " +
                        "(" + id_sacramento + "," + id_sacerdote + "," + id_tipo + "," + fecha_sacramento + "); \n" + 
                        "commit;";
                System.out.println(sql);
                java.sql.Statement statement = conexion.createStatement();
                statement.executeUpdate(sql);
            } catch (SQLException ex) {
                Configuraciones.setWarningMsg("" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_registrarMouseClicked

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered
        btn_registrar.setBackground(new Color(255,214,129));
    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited
        btn_registrar.setBackground(new Color(255,192,69));
    }//GEN-LAST:event_btn_registrarMouseExited

    private void btn_refrescar_tablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseClicked
        try {
            limpiarTabla(modelo_sacerdotes);
            limpiarTabla(modelo_tipos);
            limpiarTabla(modelo_sacramentos);
            consultarSacerdotes();
            consultarTipos();
            consultarSacramentos();
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_refrescar_tablasMouseClicked

    private void btn_refrescar_tablasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseEntered
        btn_refrescar_tablas.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_refrescar_tablasMouseEntered

    private void btn_refrescar_tablasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescar_tablasMouseExited
        btn_refrescar_tablas.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_refrescar_tablasMouseExited

    private void btn_rollbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseClicked
        try {
            String sql = "rollback;";
            java.sql.Statement statement = conexion.createStatement();
            statement.executeUpdate(sql);
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }//GEN-LAST:event_btn_rollbackMouseClicked

    private void btn_rollbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseEntered
        btn_rollback.setBackground(new Color(10,163,204));
    }//GEN-LAST:event_btn_rollbackMouseEntered

    private void btn_rollbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rollbackMouseExited
        btn_rollback.setBackground(new Color(10,145,171));
    }//GEN-LAST:event_btn_rollbackMouseExited
    
    public void consultarSacerdotes() throws SQLException{
        try {
            String sql = " select id_sacerdote, nombre_sacerdote from sacerdote order by id_sacerdote; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[2];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                modelo_sacerdotes.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    public void consultarTipos() throws SQLException{
        try {
            String sql = " select id_tipo, nombre_tipo from tipo where id_tipo " +
                         " not in ('00004', '00005', '00006') order by id_tipo; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[2];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                modelo_tipos.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    public void consultarSacramentos() throws SQLException{
        try {
            String sql = " select id_sacramento, nombre_sacerdote, nombre_tipo, fecha_sacramento "
                    + " from sacramento inner join sacerdote on sacramento.id_sacerdote = sacerdote.id_sacerdote "
                    + " inner join tipo on sacramento.id_tipo = tipo.id_tipo order by id_sacramento; ";
            java.sql.Statement statement = conexion.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            String[] filas = new String[4];
            while(rs.next()){
                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                modelo_sacramentos.addRow(filas);
              }
        } catch (SQLException ex) {
            Configuraciones.setWarningMsg("" + ex.getMessage());
        }
    }
    
    public void limpiarTabla(final DefaultTableModel model) {
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sacramentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sacramentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sacramentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sacramentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sacramentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_refrescar_tablas;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_rollback;
    private javax.swing.JTextField fecha_sacramento_input;
    private javax.swing.JSeparator fecha_sacramento_separator;
    private javax.swing.JLabel fecha_sacramento_text;
    private javax.swing.JLabel icon_window;
    private javax.swing.JTextField id_sacerdote_input;
    private javax.swing.JSeparator id_sacerdote_separator;
    private javax.swing.JLabel id_sacerdote_text;
    private javax.swing.JTextField id_sacramento_input;
    private javax.swing.JSeparator id_sacramento_separator;
    private javax.swing.JLabel id_sacramento_text;
    private javax.swing.JTextField id_tipo_input;
    private javax.swing.JSeparator id_tipo_separator;
    private javax.swing.JLabel id_tipo_text;
    private javax.swing.JScrollPane jScroll_table_1;
    private javax.swing.JScrollPane jScroll_table_2;
    private javax.swing.JScrollPane jScroll_table_3;
    private javax.swing.JLabel sacerdotes_text;
    private javax.swing.JLabel sacramentos_celebrados_text;
    private javax.swing.JTable table_sacerdotes;
    private javax.swing.JTable table_sacramentos_celebrados;
    private javax.swing.JTable table_tipos_sacramentos;
    private javax.swing.JLabel tipos_sacramentos_text;
    private javax.swing.JLabel title_window;
    // End of variables declaration//GEN-END:variables
}
